from enum import Enum


class DatabaseCollectionNames(str, Enum):

    MESSAGES_COLLECTION_NAME = "MESSAGES_COLLECTION_NAME"
    USER_ACTIONS_COLLECTION_NAME = "USER_ACTIONS_COLLECTION_NAME"
    DASHBOARD_COLLECTION_NAME = "DASHBOARD_COLLECTION_NAME"
    USER_FILTERS_COLLECTION_NAME = "USER_FILTERS_COLLECTION_NAME"
    USER_PROFILE_COLLECTION_NAME = "USER_PROFILE_COLLECTION_NAME"
    CLIENT_COLLECTION_NAME = "CLIENTS_COLLECTION_NAME"
    UNITS_COLLECTION_NAME = "UNITS_COLLECTION_NAME"
    DEVELOPERS_COLLECTION_NAME = "DEVELOPERS_COLLECTION_NAME"
    SHARING_DATA_COLLECTION_NAME = "SHARING_DATA_COLLECTION_NAME"
    PROJECTS_COLLECTION_NAME = "projects"
    SHARE_COLLECTION_NAME = "SHARED_LINKS_COLLECTION"
    AVAILABLE_MEETINGS_COLLECTION = "AVAILABLE_MEETINGS_COLLECTION"
    BOOKED_MEETINGS_COLLECTION = "BOOKED_MEETINGS_COLLECTION"
    SALES_EMPLOYEES_COLLECTION_NAME = "SALES_EMPLOYEES_COLLECTION_NAME"
    SUB_MESSAGES_COLLECTION_NAME = "MESSAGES_SUB_COLLECTION_NAME"
    IMAGES_COLLECTION_NAME = "IMAGES_COLLECTION_NAME"
    WHATSAPP_TEMPORARY_MESSAGE_COLLECTION_NAME = "WHATSAPP_TEMPORARY_MESSAGE"
